-- AlterEnum
ALTER TYPE "TipoNotifica" ADD VALUE 'CODA_INGRESSO';
ALTER TYPE "TipoNotifica" ADD VALUE 'CODA_PROMOZIONE';
ALTER TYPE "TipoNotifica" ADD VALUE 'CODA_SCADENZA';

-- AlterEnum
ALTER TYPE "TipoEvento" ADD VALUE 'CODA_INGRESSO';
ALTER TYPE "TipoEvento" ADD VALUE 'CODA_PROMOZIONE';
ALTER TYPE "TipoEvento" ADD VALUE 'CODA_SCADENZA';
ALTER TYPE "TipoEvento" ADD VALUE 'CODA_ANNULLATA';
